services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-open-webui-ui
    ports:
      - "8080:8080"
    volumes:
      - ~/.open-webui:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
